version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    security-updates: true
    rebase-strategy: auto
    labels:
      - "dependencies"
      - "security"
      - "general"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    security-updates: true
    rebase-strategy: auto
    labels:
      - "dependencies"
      - "security"
      - "general"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    security-updates: true
    rebase-strategy: auto
    labels:
      - "dependencies"
      - "security"
      - "general"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    security-updates: true
    rebase-strategy: auto
    labels:
      - "dependencies"
      - "security"
      - "general"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    security-updates: true
    labels:
      - "dependencies"
      - "github-actions"
      - "general"
